<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>destinationInput_textField</name>
   <tag></tag>
   <elementGuidId>2aa75571-deaf-4ee3-a406-0a1d8610150f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='hero-section']//input[@id='destination-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='hero-section']//input[@id='destination-input']</value>
   </webElementProperties>
</WebElementEntity>
