<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first_HotelList_text</name>
   <tag></tag>
   <elementGuidId>e6c30fac-34e7-42e7-a9f8-7dbb7a0510d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/main/div/div[2]/div[2]/div[2]/div[2]/div/a/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/main/div/div[2]/div[2]/div[2]/div[2]/div/a/div/h3</value>
   </webElementProperties>
</WebElementEntity>
