<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lanjutkanSebagai_btn</name>
   <tag></tag>
   <elementGuidId>df067c22-0b89-4cde-a606-b68b29bf0997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@name='__CONFIRM__']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@name='__CONFIRM__']</value>
   </webElementProperties>
</WebElementEntity>
