<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightFrom_textfield</name>
   <tag></tag>
   <elementGuidId>4ef1e0a7-8be8-4194-805c-a764d799168d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formhome&quot;]/div/div/div[1]/div[3]/div[2]/div[2]/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formhome&quot;]/div/div/div[1]/div[3]/div[2]/div[2]/div[2]/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
