<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaLengkap_textField</name>
   <tag></tag>
   <elementGuidId>4bb1f5ba-3dcd-4bab-a9f8-f9a707728b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'col-xs-9')]//input[@class='input-list-autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'col-xs-9')]//input[@class='input-list-autocomplete']</value>
   </webElementProperties>
</WebElementEntity>
