<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaLengkap_detail_textField</name>
   <tag></tag>
   <elementGuidId>353d0b52-d0ee-41f9-9829-baffa558e8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'error')]//input[contains(@class,'input-list-autocomplete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'error')]//input[contains(@class,'input-list-autocomplete')]</value>
   </webElementProperties>
</WebElementEntity>
